### ISSUE TITLE
Client limited to 1440p

### ISSUE THREAD

**Issue by EricEhmke** [EricEhmke/RunescapeBots#2]
Bot is currently limited to only working on a 1440p screen resolution in resizeable mode

**Comment by EricEhmke** [comment]
Bot now works in fixed window mode only

**Comment by LCapitani** [comment]
Hey Eric,

Quick question about your OSRS update to the python based GE march flipper - I seem to be unable to get it working on Mac. I simply get the error message: 

"Could not detect a Runescape Window, script aborting”

Any ideas?

Thanks for your time

**Comment by EricEhmke** [comment]
If there are no limitations to pyautogui on Mac my first suspicion would be that the main ge window that pyautogui is looking for doesn't look like the screenshot I supplied.

Do you have osrs open in fullscreen on your 1440p display when you're kicking off the script? If you're starting the script and switching to the window all on the same display I would add a sleep() to the script to give you time to open osrs fully. You could also take your own main ge window screenshot. 

If this doesn't help I can take a look later. Phone posting atm.

**Comment by LCapitani** [comment]
Might you tell me the location of this screenshot? I cannot locate it thanks!

**Comment by EricEhmke** [comment]
Tools/screenshots/ge_bottom_right.png

screenshots.py consists of a map of what the items are. It's not the
cleanest way to do it.

**Comment by LCapitani** [comment]
Aha - a new error :D 

"No empty GE slots found or no items available". I am in fullscreen and 1440p display yes so something must be going on. I imagine i'll have to update all the screenshots, but should be managable :)

Thanks for your help so far!

**Comment by EricEhmke** [comment]
No worries & you're welcome. I can't remember why I didn't just write the
whole thing in fixed mode which should avoid this problem. It was either on
my to-do or there was another reason I decided against it. The whole thing
would be more robust if it was based in fixed mode but you'd have to update
all of the screenshots & some of the math that moves the mouse around. Easy
but time consuming.

**Comment by LCapitani** [comment]
ayy my coding skills are very basic so i doubt i'd be able to do it haha, although i'd like to make my own bot so i might get to it haha. Will take the screenshot approach for now :)

**Comment by EricEhmke** [comment]
I started this project when my skills were very basic, now I am lucky enough to get paid for it. Just stick to it and work your way through the code, you may find yourself going deeper than you expect. Good luck!
